### PR TITLE
I did a bunch of cool stuff. Hopefully it helps!

### PR DESCRIPTION
**Pull request by leandrosilva**
I added those wkhtmltox files for Windows (.dll + .h), an example folder containing the README example (very slightly modified), a Makefile, and a .gitignore file. Also I made a change in the cgo directives to consider -L additionally to -l. And finally, I added a bunch of new thing in the README.

### CODE REVIEW

**Comment by adrg** [comment]
Hi @leandrosilva. Sorry for the late response. Thank you for the PR and your interest in the library. Could you split this PR into multiple ones, excluding the first few commits (the ones before the new package interface), so I can merge them in gradually?

Maybe something like this:
PR1: make `Object.setOption` public and adding the `WindowStatus` property.
PR2: adding the working examples. If the HTTP converter example does not work properly, I don't think it should be added to the repository.
PR3: adding `.gitignore` and updating `README.md` if necessary.

Regarding the concurrency problem, can you post all your findings in issue https://github.com/adrg/go-wkhtmltopdf/issues/3? I will keep that issue open until we hopefully find a solution to the problem and we can discuss everything related to it there.

I'm not sure about adding the `.h` and `.dll` files inside the repository. I don't really like having
`#cgo LDFLAGS: -L${SRCDIR}/wkhtmltox -lwkhtmltox` in the source files, so that the linker always looks in `SRCDIR` for `libwkhtmltox`. Is there a way we can make this a bit more configurable? I think it's a bit cumbersome having to copy the library files inside the repository when you want to bring your own version.

Thank you again for all your work in this PR.

**Comment by leandrosilva** [comment]
Hello.
I did 4 commits to address what you have pointed out.
Since there is no conflicts, I guess you can merge it now with no problem.
Cheers.

**Comment by adrg** [comment]
Hi @leandrosilva. Sorry for getting so late to this PR. My free time is quite limited these days. I created a new development branch and changed the base of the PR to that. I want to do a bit more work on the development branch and then I'll merge everything into the master branch on the next release of the package.

Thanks again for your contribution and your interest in the library. I want to create a contributors list section in README.md. Do you mind if I add your profile there?

**Comment by leandrosilva** [comment]
Hi @adrg.
No problem, not at all. 
My pleasure, sir.
Cheers.

**Pull request merged**
